### ISSUE TITLE
SPI Communication with External Flash

### ISSUE THREAD

**Issue by towynlin** [particle-iot-archived/bootloader#1]
The DFU will use external flash storage to keep multiple copies of firmware from wireless updates.  Step 1 is to implement the SPI communication with the external flash chip.

**Comment by satishgn** [comment]
SPI communication with Serial Flash is not working.
Verified the connections and found no fault in soldering.
I tried both SPI modes: 0 and 3 with no success.
I am trying to read the JEDEC ID of the flash as a simple test by calling sFLASH_Init() in main().
For testing, I've disabled CC3000 by commenting the SPARK_WLAN_ENABLE define.
Still debugging this issue at present.

**Comment by satishgn** [comment]
My mistake -  It was use of hardcoded SPI1 instead of SPI2 in sst25vf_spi.c file.
The SPI communication with Serial Flash is working now.
I am working on the mavin base code right now. I will move the necessary Serial Flash related files to DFU project in the coming few days after implementing and testing the necessary functions.

**Comment by towynlin** [comment]
Perfect. Thanks for the update.

**Comment by satishgn** [comment]
Completed SPI Flash Driver Implementation in marvin base code.
For testing Serial Flash, uncomment the SPARK_SFLASH_ENABLE define in platform_config.h
and uncomment sFLASH_SelfTest(); in main.c
I will now include the spi flash files in DFU project.

**Comment by satishgn** [comment]
Integrated Serial External Flash Driver code in DFU project.
Closing this issue.
